### ISSUE TITLE
Missing Paper in Few Shot Object Detection Category

### ISSUE THREAD

**Issue by QiyaoWei** [amusi/CVPR2023-Papers-with-Code#104]
Dear all,

I am recommending the addition of the following missing paper in the FSOD Category---

Paper name: Beyond Max-Margin: Class Margin Equilibrium for Few-shot Object Detection
Paper link: https://openaccess.thecvf.com/content/CVPR2021/papers/Li_Beyond_Max-Margin_Class_Margin_Equilibrium_for_Few-Shot_Object_Detection_CVPR_2021_paper.pdf
Paper code: https://github.com/Bohao-Lee/CME

Paper name: UniT: Unified Knowledge Transfer for Any-shot
Object Detection and Segmentation
Paper link: https://openaccess.thecvf.com/content/CVPR2021/papers/Khandelwal_UniT_Unified_Knowledge_Transfer_for_Any-Shot_Object_Detection_and_Segmentation_CVPR_2021_paper.pdf
Paper code: https://github.com/ubc-vision/UniT

Paper name: Generalized Few-Shot Object Detection without Forgetting
Paper link: https://openaccess.thecvf.com/content/CVPR2021/papers/Fan_Generalized_Few-Shot_Object_Detection_Without_Forgetting_CVPR_2021_paper.pdf
Paper code: None

Paper name: Transformation Invariant Few-Shot Object Detection
Paper link: https://openaccess.thecvf.com/content/CVPR2021/papers/Li_Transformation_Invariant_Few-Shot_Object_Detection_CVPR_2021_paper.pdf
Paper code: None

**Comment by amusi** [comment]
感谢大佬分享。这两天正在整理2D目标检测（含Few-shot）的论文，预计明天更新完毕，感谢分享~
