### ISSUE TITLE
Could you please add our work into the list?

### ISSUE THREAD

**Issue by ChunLLee** [amusi/CVPR2023-Papers-with-Code#171]
Hi thank you for this awesome work!

Could you please add our 2023 CVPR paper #5884 into the list?

Our proposed FOCUS model jointly solves 3D face reconstruction and outlier (those parts that are not regarded as faces) segmentation under weak supervision.

Paper at: https://arxiv.org/pdf/2106.09614.pdf
Codes at:
https://github.com/unibas-gravis/Occlusion-Robust-MoFA

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
