### ISSUE TITLE
could you help to add our CVPR 2023 paper on 3D point cloud?

### ISSUE THREAD

**Issue by PolyLiYJ** [amusi/CVPR2023-Papers-with-Code#172]
Hi, could you help to add our CVPR 2023 paper on 3D point cloud?
Title: Physical-World Optical Adversarial Attacks on 3D Face Recognition
Paper: https://arxiv.org/abs/2205.13412
Code: https://github.com/PolyLiYJ/SLAttack.git

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
