### ISSUE TITLE
Adding request.

### ISSUE THREAD

**Issue by Haiyang-W** [amusi/CVPR2023-Papers-with-Code#173]
Paper name/title: DSVT: Dynamic Sparse Voxel Transformer with Rotated Sets
Paper link: https://arxiv.org/abs/2301.06051
Code link: https://github.com/Haiyang-W/DSVT

Please put it in the [3D Object Detection](https://github.com/amusi/CVPR2023-Papers-with-Code#3D-Object-Detection) chapter of the README.md. Thanks very much! A very good repo.

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
