### ISSUE TITLE
Please add our CVPR2023 paper DexArt to Robotics

### ISSUE THREAD

**Issue by Kami-code** [amusi/CVPR2023-Papers-with-Code#189]
Here is our CVPR2023 paper: DexArt: Benchmarking Generalizable Dexterous Manipulation with Articulated Objects

Code: https://github.com/Kami-code/dexart-release
Homepage: https://www.chenbao.tech/dexart/

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
