### ISSUE TITLE
Please add our CVPR2023 paper MARLIN to Video Understanding

### ISSUE THREAD

**Issue by ControlNet** [amusi/CVPR2023-Papers-with-Code#190]
Hi,

Please add our CVPR 2023 paper to Video Understanding section:

Title: MARLIN: Masked Autoencoder for facial video Representation LearnINg
Topic: Facial Video Representation Learning
Paper: https://arxiv.org/abs/2211.06627
Code: https://github.com/ControlNet/MARLIN

Thank you very much!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
