### ISSUE TITLE
Please add our CVPR2023 paper to Backbone and Vision Transformer

### ISSUE THREAD

**Issue by changsn** [amusi/CVPR2023-Papers-with-Code#191]
Hi,
Please add our CVPR2023 paper to Backbone and Vision Transformer.
Name: Making Vision Transformers Efficient from A Token Sparsification View
Link: https://arxiv.org/abs/2303.08685
Code: https://github.com/changsn/STViT-R

Thank you!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
